// <auto-generated />
namespace AntiDepressantWebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddGeoLocationProp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddGeoLocationProp));
        
        string IMigrationMetadata.Id
        {
            get { return "201810190313078_Add GeoLocation Prop"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
